### PR TITLE
Make static site standalone

### LINKED ISSUE #69: Update XSLT for DHQ indexes to XSLT 2 or 3, then fix sorting of author names
While testing my fixes for broken links, I discovered a bug in the Authors index: "Sánchez-Salido" is sorted in between "Smith" and "Snickars", not up next to another "Sanchez".

Screenshot of author Sánchez-Salido sorting between Smith and Snickars

The reason appears to be the XSLT code in `author_index.xsl` which lower-cases capital letters and removes any other characters that aren't a–z (read: diacritics aren't allowed). With this code in place, I believe "Sánchez-Salido" is given a sort key of "snchezsalido".

The complicated code required to make sortable keys is insufficient. To fix it would require an awful lot of complex and unreadable XSLT 1.0 code. *Or* we could upgrade to XSLT 2.0 or 3.0, and just use `lower-case()` to generate that sort key. I recommend the latter!

### LINKED ISSUE #73: fix incorrect alphabetization in Author index
The entry for:
```
Čejka, Martin, Czech University of Life Sciences Prague
[Cuneiform Stroke Recognition and Vectorization in 2D Images](http://www.digitalhumanities.org/dhq/vol/18/1/000733/000733.html), 2024: v18 n1, [co-authored]

```
is being alphabetized as "ejka" (the initial Č is being ignored)

### PR DESCRIPTION
**Pull request by amclark42**
I would like my reviewer(s) to check out this branch and run either `makeInternalPreview` or `generateSite`.

- Does the process work on your machine?
  - Is there anything that could be better explained?
- Are you able to navigate around the static site in your browser, without using a server?
- Are images being displayed correctly? In an article? In the footer?
- Does the Javascript to expand abstracts work?
- From a development standpoint, does the `path_to_home` parameter seem like something you can use?

I'd love feedback on the revised `author_index.xsl` and `title_index.xsl`. **However**, the `diff` will not help; you'll have to read the file in an editor. If there are any things I can make clearer or better, please let me know!

### Context

The main goal of this branch was to make the static site work on its own, without the need to fire up a server. All links to resources within DHQ are now either absolute paths or relative. When it isn't easy to determine a direct path from one page to another, the new parameter `path_to_home` will allow the XSLT stylesheets to build a path from the DHQ "home" directory to the target page.

Other notable changes:

- The DHQ Javascript file is loaded from an external file, which will allow us to use characters that are restricted in XHTML. Previously, some JS events did not work in the static site, because less-than signs were serialized as `&lt;`, which the browser could not parse.
- DHQ CSS has been rewritten to remove rules that used [Internet Explorer's "dynamic property"](https://learn.microsoft.com/en-us/archive/blogs/ie/ending-expressions) `expression()`.
  - The main DHQ stylesheet, `dhq.css`, now attempts to set sane image widths, rather than calculating based on the image's width. (I'm not quite sure I got these right.)
  - The `dhq_screen.css` stylesheet now uses [CSS media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries) to override CSS rules when the screen is larger than 800 pixels wide.
- I also removed the webpage background image. Instead, the sidebar has a background color and a border that looks about the same as the "bar" image. This should help future mobile-friendly styling efforts.
- The public Author and Title indexes have been completely refactored to use XSLT 3.0. Comments have been added to make the stylesheets more readable and maintainable. The work of sorting is all done in a single transformation; there is no more need for `author_sort.xsl` and `title_sort.xsl`.
  - A new stylesheet `common-components.xsl` houses variables, templates, and functions that I imagine could be used in at least two DHQ stylesheets. I did not go back to other stylesheets to import the new common one.
  - Sorting is now done such that characters with diacritics appear next to those without. (Resolves #69; resolves #73.)
    - `title_index.xsl` adds the ability to remove leading stopwords for titles in German, Spanish, Portuguese, and French.
  - When the TEI encoding indicates it, quotation marks in article titles are rendered in the XHTML. (Italicization is not, but could be, very easily.)
  - Language codes are represented with `@xml:lang` and `@lang` attributes in the XHTML.
  - The intra-index navbar and navigation links have been tweaked to be useful to screen readers.

### CODE REVIEW

**Comment by sydb** [comment]
Checkedout branch, ran `makeInternalPreview`:
- Does the process work on your machine? — **yup**
  - Is there anything that could be better explained? — explained where?
- Are you able to navigate around the static site in your browser, without using a server? — **yup**
- Are images being displayed correctly? In an article? — **yup** In the footer? — **probably**, but all I see is the NEH logo and the Creative Commons icons; is there something else?
- Does the Javascript to expand abstracts work? — **no**, I don’t think so, but I am not sure; I do not think I came across any abstracts that were folded and thus needed expansion; where would they be?
- From a development standpoint, does the `path_to_home` parameter seem like something you can use? — **not yet**. Where is it defined? (There are 10 `<xsl:aram name="path_to_home">` elements in 10 different files; of those only 4 look like good candidates to be the definition as they have default values of `.` or null.)

Then tried the same with `generateSite`. Overall seemed to be the same results.

In both cases I could not deduce when clicking a link behaved in the normal fashion ("_self") vs opening in a new tab ("_blank"). This might have just been me not paying strict enough attention, though.

**Comment by jawalsh** [comment]
Checkedout branch, ran `generateSite`:

- Does the process work on your machine? — yes
- Is there anything that could be better explained? – nothing immediately comes to mind
- Are you able to navigate around the static site in your browser, without using a server? — yes
- Are images being displayed correctly? 
	- In an article? — yes 
	- In the footer? — yes
- Does the Javascript to expand abstracts work? — yes. tested with both english-only and multilingual articles.
- From a development standpoint, does the `path_to_home parameter` seem like something you can use? — I didn't dig into this too much, but based how I see you using it, it definitely looks helpful. I'd like to know more about how/where you're setting it and how you are determining the correct value for each setting.

Then tried the same with `makeInternalPreview`. 

Everything worked as above **except**…
- Does the Javascript to expand abstracts work? — yes, when `do.proofing.full` is set to `true`; **no**, when `do.proofing.full` is set to `false`.

*Aside:* I wonder if we could use something like the following in our `build.xml` file to avoid having to set `-lib common/lib/saxon/` on the command line when we run our Ant tasks?

```
<classpath>
	<pathelement path="common/lib/saxon/saxon-he-12.4.jar"/>
</classpath>
```

**Comment by amclark42** [comment]
@jawalsh @sydb Many thanks to both of you!

I'll add some explanatory comments on those `$path_to_home` parameters. The short version is that, like a lot of the parameters common among the DHQ stylesheets, `$path_to_home` can sometimes be set generically for most cases, and sometimes it is overridden in stylesheets for specific use cases. Its value is used most in `head.xsl`, but other use cases exist in other stylesheets.

The Javascript not working in `internalPreview` mode seems like a quick thing to fix too...

**Comment by amclark42** [comment]
> Aside: I wonder if we could use something like the following in our build.xml file to avoid having to set -lib common/lib/saxon/ on the command line when we run our Ant tasks?

@jawalsh I think I tried that, either here or with a WWP project. When I looked it up here's the answer I found (it's also [quoted in build.xml](https://github.com/Digital-Humanities-Quarterly/dhq-journal/blob/static_site_generation/build.xml#L30-L39)):

> From the Saxon documentation on XSLT with Ant:
      "In particular, the classpath attribute of the xslt task element has been 
      unreliable: the safest approach is to ensure that the Jar files needed to run 
      Saxon are present on the externally-specified classpath (the classpath at the 
      point where Ant is invoked), rather than relying on the task-specific 
      classpath."
    https://www.saxonica.com/html/documentation11/using-xsl/xsltfromant.html

Even before we got started on this project, I used XSLT and Ant so much, I set myself up so that I never need to add the `-lib` option to get Saxon loaded in on Ant invocation. You can do that too by creating a symlink to the Saxon JARs in `~/.ant/lib`. For example, mine looks like this:
```shell
(: 2024-08-30, DHQ/dhq-journal :) ls -la ~/.ant/lib 
total 0
drwxr-xr-x  4 aclark  staff  128 May  2  2023 .
drwxr-xr-x  3 aclark  staff   96 Feb  2  2023 ..
lrwxr-xr-x  1 aclark  staff   42 Feb  2  2023 saxon-he-current.jar -> /Users/aclark/SaxonHE/saxon-he-current.jar
lrwxr-xr-x  1 aclark  staff   60 Feb  2  2023 xmlresolver-4.6.0.jar -> /Users/aclark/SaxonHE/SaxonHE12-0J/lib/xmlresolver-4.6.0.jar
```

It might be useful for me to add this information to the wiki, for folks who end up needing it on the command line.

**Comment by amclark42** [comment]
@jawalsh @sydb I fixed the Javascript issue, and added more information on `$path_to_home` throughout the stylesheets where it's set! Please take a look when you have a chance, and do let me know if there's anything else I can make clearer.

**Review by jawalsh — APPROVED** [review]

**Review by jawalsh — APPROVED** [review]

**Pull request merged**
