### PR TITLE
add validation to static site generation build file

### PR DESCRIPTION
**Pull request by sydb**
This is not intended to be the end of the road of putting validation into the build process, rather it is intended to be enough for now. I.e., working well enough that I can use it PRN and can get started in folding UVEPSSS (University of Victoria Endings Project Static Search System) into the static site.

### CODE REVIEW

**Comment by amclark42** [comment]
@sydb I tried running `ant help` and immediately got an error:

```shell
(: 2024-02-15, DHQ/dhq-journal :) ant help
Buildfile: /Users/aclark/Documents/DHQ/dhq-journal/build.xml

BUILD FAILED
/Users/aclark/Documents/DHQ/dhq-journal/build.xml:63: taskdef class com.thaiopensource.relaxng.util.JingTask cannot be found
 using the classloader AntClassLoader[]

Total time: 0 seconds
```

I need to switch gears so I can't dissect this to figure out what happened, but I feel it's a real downgrade for `ant help` not to work out-of-the-box. Is there a way we can condition the loading of the custom task (?) on whether we're actually going to need it?

**Comment by sydb** [comment]
Wow, thanks, @amclark42; I did not realize at all that that would happen. But no, rather than test “do we need it”, I just removed it, because we don’t. The only sequela is that if & when this gets merged I want to avoid “squash and merge” so that the code I have just deleted (which calls `jing` directly from ant) is in the commit history _somewhere_.

**Comment by amclark42** [comment]
Thanks for fixing it so fast, @sydb! I'll take another look.

**Comment by sydb** [comment]
1. (Move `xmlstarlet` suggestion) — Good idea.
2. “Open” vs “closed” — I prefer to leave it as is, since they are the technically correct terms for the categories of schema being used. Yes, there is only one open schema language anybody ever uses (Schematron, be it 1.x or ISO), and we are **really** unlikely to ever switch from RELAX NG to some other closed schema language, but nonetheless I like reminding folks of the basic underlying difference, and thus why we want both.
3. Probably a good idea, but I would much prefer to merge it now, with an aim towards fixing it someday, rather than hold up static search for getting this right.

**Comment by sydb** [comment]
Number (1) above fixed.
And yes, I think we should just ignore the pathing errors for now.

**Comment by amclark42** [comment]
@sydb Wait, no, we can't ignore the pathing issues! There's no point in merging this into the static site branch if `validate` only works for Syd Bauman and no one else, IMO.

**Comment by sydb** [comment]
I’m sorry, I don’t understand. Precisely the same set of people use this branch as use the static_site_generation branch: no one except us, right? Seems to me the argument not to merge unless it works for everyone applies to the main branch, not to these.

**Comment by amclark42** [comment]
I see.

Here's where I'm coming from: I'm treating `static_site_generation` as a nearly-complete branch that will be ready to be merged into `main` ASAP. I've worked really hard to make sure that the Ant targets work for everyone across multiple machines. I do not like the idea of folding in untested validation processes that will work for everyone someday, but until then it's just a thing that only works on Syd's computer and that everyone else has to ignore.

It seems to me that if properly finishing validation needs to wait until you've finished staticSearch, the incomplete work should stay in its branch until you have the time to make it work for everyone.

**Comment by jawalsh** [comment]
I agree with Ash. We hope to merge this branch with main soon. And some time after that, we'll be promoting it as a better, easier way to do community development. So we'll want it to work for lots of people on lots of different machines with as little confusion as possible.

**Comment by juliaflanders** [comment]
I think the community development point is important here--we already have people (e.g. Rebecca Koeser on the ACH board) who have demonstrated interest in contributing code for things like improved accessibility, so it would be great to treat the static site code not as an internal arrangement but as a more public contributory platform.

**Comment by sydb** [comment]
OK, going with the majority, here.
We do not have a “blocked” label, so I used “wont’t fix”, not as in “will not ever fix” but as in “will not merge now, and may never, depending”.
We can re-open if & when …

**Pull request closed without merging**
